### ISSUE TITLE
 error VsixPub0004 error while publishing extensions

### ISSUE THREAD

**Issue by alvinseville7cf** [alvinseville7cf/CSharp-Snippet-Collection#13]
`VsixPublisher publish -payload "CSharpSnippetCollection\bin\Release\CSharpSnippetCollection.vsix" -publishManifest "publishmanifest.json"` produces:
```
VSSDK: error VsixPub0004 : Encountered an exception when publishing the vsix from 'System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Part URI is not valid per rules defined in the Open Packaging Conventions specification.
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.PartExists(Uri partUri)
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Publisher.TryExtractFileFromVsix(String vsixPath, String relativePathInPackage, String outputPath)
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Publisher.<PublishCoreAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Commands.PublishCommand.Execute(IReadOnlyDictionary`2 selectedArguments)
---> (Inner Exception #0) System.ArgumentException: Part URI is not valid per rules defined in the Open Packaging Conventions specification.
   at System.IO.Packaging.PackUriHelper.ValidatePartUri(Uri partUri)
   at System.IO.Packaging.Package.GetPartHelper(Uri partUri)
   at System.IO.Packaging.Package.PartExists(Uri partUri)
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Publisher.TryExtractFileFromVsix(String vsixPath, String relativePathInPackage, String outputPath)
   at Microsoft.VisualStudio.Sdk.VsixPublisher.Publisher.<PublishCoreAsync>d__9.MoveNext()<---
': C:\Users\Alvin\source\repos\CSharp-Snippet-Collection\CSharpSnippetCollection\bin\Release\CSharpSnippetCollection.vsix
```

**Comment by alvinseville7cf** [comment]
Reddit [topic](https://www.reddit.com/r/VisualStudio/comments/noeeee/error_vsixpub0004_error_while_publishing_extension/) created.
